/**
 * File: Address.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Address.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Address.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Address.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_street
 * @note { e.g. "Somethingstreet 17a" }
 * @param new_var the new value of m_street
 */
void Address::setStreet ( string new_var ) {
  m_street = new_var;
}

/**
 * Get the value of m_street
 * @note { e.g. "Somethingstreet 17a" }
 * @return the value of m_street
 */
string Address::getStreet ( ) {
  return m_street;
}

/**
 * Set the value of m_optional
 * @note { e.g. "c/o Mr. X" }
 * @param new_var the new value of m_optional
 */
void Address::setOptional ( string new_var ) {
  m_optional = new_var;
}

/**
 * Get the value of m_optional
 * @note { e.g. "c/o Mr. X" }
 * @return the value of m_optional
 */
string Address::getOptional ( ) {
  return m_optional;
}

/**
 * Set the value of m_zip
 * @note { e.g. "01234567890" }
 * @param new_var the new value of m_zip
 */
void Address::setZip ( int new_var ) {
  m_zip = new_var;
}

/**
 * Get the value of m_zip
 * @note { e.g. "01234567890" }
 * @return the value of m_zip
 */
int Address::getZip ( ) {
  return m_zip;
}

/**
 * Set the value of m_city
 * @note { e.g. "Tokyo" }
 * @param new_var the new value of m_city
 */
void Address::setCity ( string new_var ) {
  m_city = new_var;
}

/**
 * Get the value of m_city
 * @note { e.g. "Tokyo" }
 * @return the value of m_city
 */
string Address::getCity ( ) {
  return m_city;
}

/**
 * Set the value of m_country
 * @note { e.g. "Japan" }
 * @param new_var the new value of m_country
 */
void Address::setCountry ( string new_var ) {
  m_country = new_var;
}

/**
 * Get the value of m_country
 * @note { e.g. "Japan" }
 * @return the value of m_country
 */
string Address::getCountry ( ) {
  return m_country;
}

/**
 * Set the value of m_state
 * @note { e.g. "Toyko-to" }
 * @param new_var the new value of m_state
 */
void Address::setState ( string new_var ) {
  m_state = new_var;
}

/**
 * Get the value of m_state
 * @note { e.g. "Toyko-to" }
 * @return the value of m_state
 */
string Address::getState ( ) {
  return m_state;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


