/**
 * File: Contact.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Contact.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Contact.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Contact.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_email
 * @note {e.g. "bjoern@rennhak.de" }
 * @param new_var the new value of m_email
 */
void Contact::setEmail ( string new_var ) {
  m_email = new_var;
}

/**
 * Get the value of m_email
 * @note {e.g. "bjoern@rennhak.de" }
 * @return the value of m_email
 */
string Contact::getEmail ( ) {
  return m_email;
}

/**
 * Set the value of m_phone
 * @note { e.g. "+81 (0) 3 123 456 789 / -ext 799" }
 * @param new_var the new value of m_phone
 */
void Contact::setPhone ( string new_var ) {
  m_phone = new_var;
}

/**
 * Get the value of m_phone
 * @note { e.g. "+81 (0) 3 123 456 789 / -ext 799" }
 * @return the value of m_phone
 */
string Contact::getPhone ( ) {
  return m_phone;
}

/**
 * Set the value of m_fax
 * @note { e.g. "+81 (0) 3 123 456 789 / -ext 799" }
 * @param new_var the new value of m_fax
 */
void Contact::setFax ( string new_var ) {
  m_fax = new_var;
}

/**
 * Get the value of m_fax
 * @note { e.g. "+81 (0) 3 123 456 789 / -ext 799" }
 * @return the value of m_fax
 */
string Contact::getFax ( ) {
  return m_fax;
}

/**
 * Set the value of m_www
 * @note {e.g. "http://www.example.com" }
 * @param new_var the new value of m_www
 */
void Contact::setWww ( string new_var ) {
  m_www = new_var;
}

/**
 * Get the value of m_www
 * @note {e.g. "http://www.example.com" }
 * @return the value of m_www
 */
string Contact::getWww ( ) {
  return m_www;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


