/**
 * File: Equipment.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Equipment.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Equipment.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Equipment.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_name
 * @note { e.g. "" }
 * @param new_var the new value of m_name
 */
void Equipment::setName ( string new_var ) {
  m_name = new_var;
}

/**
 * Get the value of m_name
 * @note { e.g. "" }
 * @return the value of m_name
 */
string Equipment::getName ( ) {
  return m_name;
}

/**
 * Set the value of m_description
 * @note { e.g. "" }
 * @param new_var the new value of m_description
 */
void Equipment::setDescription ( string new_var ) {
  m_description = new_var;
}

/**
 * Get the value of m_description
 * @note { e.g. "" }
 * @return the value of m_description
 */
string Equipment::getDescription ( ) {
  return m_description;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


