/**
 * File: Frame.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Frame.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Frame.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Frame.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_timestamp
 * @note { e.g. "Thu Jul  2 00:54:22 JST 2009" }
 * @param new_var the new value of m_timestamp
 */
void Frame::setTimestamp ( string new_var ) {
  m_timestamp = new_var;
}

/**
 * Get the value of m_timestamp
 * @note { e.g. "Thu Jul  2 00:54:22 JST 2009" }
 * @return the value of m_timestamp
 */
string Frame::getTimestamp ( ) {
  return m_timestamp;
}

/**
 * Set the value of m_epoch
 * @note { e.g. 1246463811 }
 * @param new_var the new value of m_epoch
 */
void Frame::setEpoch ( unsigned int new_var ) {
  m_epoch = new_var;
}

/**
 * Get the value of m_epoch
 * @note { e.g. 1246463811 }
 * @return the value of m_epoch
 */
unsigned int Frame::getEpoch ( ) {
  return m_epoch;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


