/**
 * File: Person.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Person.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Person.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Person.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_firstName
 * @note { e.g. "Bjoern" }
 * @param new_var the new value of m_firstName
 */
void Person::setFirstName ( string new_var ) {
  m_firstName = new_var;
}

/**
 * Get the value of m_firstName
 * @note { e.g. "Bjoern" }
 * @return the value of m_firstName
 */
string Person::getFirstName ( ) {
  return m_firstName;
}

/**
 * Set the value of m_middleName
 * @note { e.g. "J.C." }
 * @param new_var the new value of m_middleName
 */
void Person::setMiddleName ( string new_var ) {
  m_middleName = new_var;
}

/**
 * Get the value of m_middleName
 * @note { e.g. "J.C." }
 * @return the value of m_middleName
 */
string Person::getMiddleName ( ) {
  return m_middleName;
}

/**
 * Set the value of m_lastName
 * @note { e.g. "Rennhak" }
 * @param new_var the new value of m_lastName
 */
void Person::setLastName ( string new_var ) {
  m_lastName = new_var;
}

/**
 * Get the value of m_lastName
 * @note { e.g. "Rennhak" }
 * @return the value of m_lastName
 */
string Person::getLastName ( ) {
  return m_lastName;
}

/**
 * Set the value of m_organization
 * @note { e.g. "Tokyo University" }
 * @param new_var the new value of m_organization
 */
void Person::setOrganization ( string new_var ) {
  m_organization = new_var;
}

/**
 * Get the value of m_organization
 * @note { e.g. "Tokyo University" }
 * @return the value of m_organization
 */
string Person::getOrganization ( ) {
  return m_organization;
}

/**
 * Set the value of m_gender
 * @note { e.g. "TRUE" is Male, "FALSE" is FEMALE }
 * @param new_var the new value of m_gender
 */
void Person::setGender ( bool new_var ) {
  m_gender = new_var;
}

/**
 * Get the value of m_gender
 * @note { e.g. "TRUE" is Male, "FALSE" is FEMALE }
 * @return the value of m_gender
 */
bool Person::getGender ( ) {
  return m_gender;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


