/**
 * File: Picture.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Picture.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Picture.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Picture.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_height
 * @note {e.g. 124 in px}
 * @param new_var the new value of m_height
 */
void Picture::setHeight ( int new_var ) {
  m_height = new_var;
}

/**
 * Get the value of m_height
 * @note {e.g. 124 in px}
 * @return the value of m_height
 */
int Picture::getHeight ( ) {
  return m_height;
}

/**
 * Set the value of m_width
 * @note { e.g. 124 in px}
 * @param new_var the new value of m_width
 */
void Picture::setWidth ( int new_var ) {
  m_width = new_var;
}

/**
 * Get the value of m_width
 * @note { e.g. 124 in px}
 * @return the value of m_width
 */
int Picture::getWidth ( ) {
  return m_width;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


