/**
 * File: Sensor.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Sensor.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Sensor.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Sensor.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


/**
 * Set the value of m_unit
 * @note { e.g. "INCH" }
 * @param new_var the new value of m_unit
 */
void Sensor::setUnit ( string new_var ) {
  m_unit = new_var;
}

/**
 * Get the value of m_unit
 * @note { e.g. "INCH" }
 * @return the value of m_unit
 */
string Sensor::getUnit ( ) {
  return m_unit;
}

/**
 * Set the value of m_placement
 * @note { e.g. Left Sternum, 2 cm above x }
 * @param new_var the new value of m_placement
 */
void Sensor::setPlacement ( string new_var ) {
  m_placement = new_var;
}

/**
 * Get the value of m_placement
 * @note { e.g. Left Sternum, 2 cm above x }
 * @return the value of m_placement
 */
string Sensor::getPlacement ( ) {
  return m_placement;
}

// Other methods
//  


