/**
 * File: Sound.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Sound.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Sound.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Sound.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_samplerate
 * @note {e.g. "44100" in Hz}
 * @param new_var the new value of m_samplerate
 */
void Sound::setSamplerate ( int new_var ) {
  m_samplerate = new_var;
}

/**
 * Get the value of m_samplerate
 * @note {e.g. "44100" in Hz}
 * @return the value of m_samplerate
 */
int Sound::getSamplerate ( ) {
  return m_samplerate;
}

/**
 * Set the value of m_length
 * @note {e.g. "127.4" in s}
 * @param new_var the new value of m_length
 */
void Sound::setLength ( float new_var ) {
  m_length = new_var;
}

/**
 * Get the value of m_length
 * @note {e.g. "127.4" in s}
 * @return the value of m_length
 */
float Sound::getLength ( ) {
  return m_length;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


