/**
 * File: Video.h.cpp
 **/

/**
 *
 * __        ___    ____  _   _ ___ _   _  ____ 
 * \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
 *  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
 *   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
 *    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
 *
 * This file (Video.h.cpp) was Auto-generated by "Umbrello" the UML Modeller tool.
 * ( URL: http://uml.sourceforge.net/ )
 *
 * If you make changes and regenerate with Umbrello your changes *WILL* be lost.
 * Make sure you understand how MotionX works before you develop new interfaces.
 *
 * vim=ts:2
 *
 **/

/**
 *
 * (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
 *
 * @file       Video.h.cpp
 * @author     Bjoern Rennhak
 * @since      Thu Jul 2 2009 01:42:46
 * @version    <%= version %>
 * @copyright  See COPYRIGHT file for details.
 *
 **/



#include "Video.h"

// Constructors/Destructors
//  

//  
// Methods
//  


// Accessor methods
//  


// Public static attribute accessor methods
//  


// Public attribute accessor methods
//  


/**
 * Set the value of m_bitrate
 * @note {e.g. "1247.12"}
 * @param new_var the new value of m_bitrate
 */
void Video::setBitrate ( float new_var ) {
  m_bitrate = new_var;
}

/**
 * Get the value of m_bitrate
 * @note {e.g. "1247.12"}
 * @return the value of m_bitrate
 */
float Video::getBitrate ( ) {
  return m_bitrate;
}

/**
 * Set the value of m_length
 * @note { e.g. "124.1" in s }
 * @param new_var the new value of m_length
 */
void Video::setLength ( float new_var ) {
  m_length = new_var;
}

/**
 * Get the value of m_length
 * @note { e.g. "124.1" in s }
 * @return the value of m_length
 */
float Video::getLength ( ) {
  return m_length;
}

/**
 * Set the value of m_resolution
 * @note { e.g. "800x600" in px }
 * @param new_var the new value of m_resolution
 */
void Video::setResolution ( string new_var ) {
  m_resolution = new_var;
}

/**
 * Get the value of m_resolution
 * @note { e.g. "800x600" in px }
 * @return the value of m_resolution
 */
string Video::getResolution ( ) {
  return m_resolution;
}

// Protected static attribute accessor methods
//  


// Protected attribute accessor methods
//  


// Private static attribute accessor methods
//  


// Private attribute accessor methods
//  


// Other methods
//  


