#!/usr/bin/ruby
#

###
# File: %filename%
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (%filename%) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       %filename%
# @author     Bjoern Rennhak
# @since      %date% %time%
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######


