#!/usr/bin/ruby
#

###
# File: Address.rb
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (Address.rb) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       Address.rb
# @author     Bjoern Rennhak
# @since      Thu Jul 2 2009 01:41:28
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######



#
# @class Address
# @brief { Address is a abstraction which holds the address information of a person. }
# @details { }
#

class Address
  #
  # Accessor Methods
  #

  # @note { e.g. "Somethingstreet 17a" }
  attr_accessor :street

  # @note { e.g. "c/o Mr. X" }
  attr_accessor :optional

  # @note { e.g. "01234567890" }
  attr_accessor :zip

  # @note { e.g. "Tokyo" }
  attr_accessor :city

  # @note { e.g. "Japan" }
  attr_accessor :country

  # @note { e.g. "Toyko-to" }
  attr_accessor :state


  public

  protected

  private

end

