#!/usr/bin/ruby
#

###
# File: Contact.rb
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (Contact.rb) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       Contact.rb
# @author     Bjoern Rennhak
# @since      Thu Jul 2 2009 01:41:28
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######



#
# @class Contact
# @brief {Contact encapsulates everything beside an Address.}
# @details {Contact stores everything beside addresses like email, fax, phone etc.}
#

class Contact
  #
  # Accessor Methods
  #

  # @note {e.g. "bjoern@rennhak.de" }
  attr_accessor :email

  # @note { e.g. "+81 (0) 3 123 456 789 / -ext 799" }
  attr_accessor :phone

  # @note { e.g. "+81 (0) 3 123 456 789 / -ext 799" }
  attr_accessor :fax

  # @note {e.g. "http://www.example.com" }
  attr_accessor :www


  public

  protected

  private

end

