#!/usr/bin/ruby
#

###
# File: Equipment.rb
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (Equipment.rb) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       Equipment.rb
# @author     Bjoern Rennhak
# @since      Thu Jul 2 2009 01:41:28
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######



#
# @brief {Equipment can be all kind of things which is used or worn by a person. }
# @details {Equipment can be all kind of things which is either used or work by a person. These things can include a force measuring system, clothing etc.}
#

class Equipment
  #
  # Accessor Methods
  #

  # @note { e.g. "" }
  attr_accessor :name

  # @note { e.g. "" }
  attr_accessor :description


  public

  protected

  private

end

