#!/usr/bin/ruby
#

###
# File: Frame.rb
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (Frame.rb) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       Frame.rb
# @author     Bjoern Rennhak
# @since      Thu Jul 2 2009 01:41:28
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######



#
# 
#

class Frame
  #
  # Accessor Methods
  #

  # @note { e.g. "Thu Jul  2 00:54:22 JST 2009" }
  attr_accessor :timestamp

  # @note { e.g. 1246463811 }
  attr_accessor :epoch


  public

  protected

  private

end

