#!/usr/bin/ruby
#

###
# File: Media.rb
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (Media.rb) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       Media.rb
# @author     Bjoern Rennhak
# @since      Thu Jul 2 2009 01:41:28
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######



#
# @class Media
# @brief {Media is a abstract base class which represents many things related to this motion capture session.}
# @details {Media is a abstract base class which represents many things related to this motion capture session. For instance  a Video, Picture, Sound files etc.}
# 
#

class Media
  #
  # Accessor Methods
  #

  # @note { e.g. "Symphony Nr. III, D Minor" } 
  attr_accessor :name

  # @note {e.g. "This is a musical piece by .... etc. etc."}
  attr_accessor :description

  # @note {e.g. "Music_01.mp3" }
  attr_accessor :filename

  # @note {e.g. "/my/location"}
  attr_accessor :path

  # @note {e.g. "Base64 encoded payload" }
  attr_accessor :data

  # @note {e.g. "MPEG Layer III"}
  attr_accessor :codec


  public

  protected

  private

end

