#!/usr/bin/ruby
#

###
# File: Person.rb
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (Person.rb) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       Person.rb
# @author     Bjoern Rennhak
# @since      Thu Jul 2 2009 01:41:28
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######



#
# @class Person
# @brief { The Person class is a representation of a natural person and all its data. }
# @details { The Person class represents a abstraction of all possible data which a natural person can have. }
#

class Person
  #
  # Accessor Methods
  #

  # @note { e.g. "Bjoern" }
  attr_accessor :firstName

  # @note { e.g. "J.C." }
  attr_accessor :middleName

  # @note { e.g. "Rennhak" }
  attr_accessor :lastName

  # @note { e.g. "Tokyo University" }
  attr_accessor :organization

  # @note { e.g. "TRUE" is Male, "FALSE" is FEMALE }
  attr_accessor :gender


  public

  protected

  private

end

