#!/usr/bin/ruby
#

###
# File: Video.rb
#######

###
#
# __        ___    ____  _   _ ___ _   _  ____ 
# \ \      / / \  |  _ \| \ | |_ _| \ | |/ ___|
#  \ \ /\ / / _ \ | |_) |  \| || ||  \| | |  _ 
#   \ V  V / ___ \|  _ <| |\  || || |\  | |_| |
#    \_/\_/_/   \_\_| \_\_| \_|___|_| \_|\____|
#
# This file (Video.rb) was Auto-generated by "Umbrello" the UML Modeller tool.
# ( URL: http://uml.sourceforge.net/ )
#
# If you make changes and regenerate with Umbrello your changes *WILL* be lost.
# Make sure you understand how MotionX works before you develop new interfaces.
#
# vim=ts:2
#
#######

###
#
# (c) 2009, Copyright, Bjoern Rennhak, The University of Tokyo
#
# @file       Video.rb
# @author     Bjoern Rennhak
# @since      Thu Jul 2 2009 01:41:28
# @version    <%= version %>
# @copyright  See COPYRIGHT file for details.
#
#######



#
# 
# 
#

class Video < Media

  #
  # Accessor Methods
  #

  # @note {e.g. "1247.12"}
  attr_accessor :bitrate

  # @note { e.g. "124.1" in s }
  attr_accessor :length

  # @note { e.g. "800x600" in px }
  attr_accessor :resolution


  public

  protected

  private

end

